--- luadbi-0.7.2/Makefile.orig	2019-01-14 10:39:17.000000000 +0100
+++ luadbi-0.7.2/Makefile	2020-04-05 20:24:34.738355081 +0200
@@ -10,7 +10,7 @@
 LUA_LDIR	?= /usr/share/lua/$(LUA_V)
 LUA_CDIR	?= /usr/lib/lua/$(LUA_V)
 
-COMMON_CFLAGS	 ?= -g -pedantic -Wall -O2 -shared -fPIC -DPIC -std=c99
+COMMON_CFLAGS	 ?= -pedantic -Wall -shared -fPIC -DPIC -std=c99
 LUA_INC		?= -I/usr/include/lua$(LUA_V)
 MYSQL_INC	?= -I/usr/include/mysql
 PSQL_INC	?= -I/usr/include/postgresql
